services:
  frontend-portal:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend-gateway

  backend-gateway:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5001
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - ELITE_TIER_ENABLED=true
    depends_on:
      - localstack

  localstack:
    container_name: sovereign_localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3,lambda,apigateway,dynamodb,kms,route53,ec2,iam
      - AWS_DEFAULT_REGION=ap-south-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"